// scripts/create_demo_users.ts
// Creates the 10 demo auth users, mirrors them into public.users, and writes
// tenant memberships + leave balances. Idempotent: re-running updates rather
// than duplicating.
//
// Required env vars (set in scripts/.env):
//   SUPABASE_URL
//   SUPABASE_SERVICE_ROLE_KEY
//
// Run with:  npx tsx create_demo_users.ts

import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

config({ path: resolve(process.cwd(), '.env') });

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in scripts/.env');
  process.exit(1);
}

const supabase = createClient(url, key, { auth: { persistSession: false } });

const TENANTS = [
  { id: '11111111-1111-1111-1111-111111111111', slug: 'acme' },
  { id: '22222222-2222-2222-2222-222222222222', slug: 'globex' },
];

const PASSWORD = 'demo1234';

type Role = 'admin' | 'manager' | 'employee' | 'viewer';

const ROLES: { role: Role; emailPrefix: string; fullName: string }[] = [
  { role: 'admin',    emailPrefix: 'admin',    fullName: 'Ada Admin' },
  { role: 'manager',  emailPrefix: 'manager',  fullName: 'Maya Manager' },
  { role: 'employee', emailPrefix: 'employee', fullName: 'Eli Employee' },
  { role: 'employee', emailPrefix: 'employee2', fullName: 'Eve Employee' },
  { role: 'viewer',   emailPrefix: 'viewer',   fullName: 'Vic Viewer' },
];

const CURRENT_YEAR = new Date().getUTCFullYear();

async function ensureAuthUser(email: string, fullName: string): Promise<string> {
  const { data: existing, error: listErr } = await supabase.auth.admin.listUsers({ perPage: 200 });
  if (listErr) throw listErr;
  const found = existing.users.find((u) => u.email === email);
  if (found) {
    // Make sure the password is what we expect so the demo works deterministically.
    await supabase.auth.admin.updateUserById(found.id, { password: PASSWORD, email_confirm: true });
    return found.id;
  }
  const { data, error } = await supabase.auth.admin.createUser({
    email,
    password: PASSWORD,
    email_confirm: true,
    user_metadata: { full_name: fullName },
  });
  if (error) throw error;
  return data.user!.id;
}

async function main() {
  const credentials: { tenant: string; role: Role; email: string; password: string }[] = [];

  for (const tenant of TENANTS) {
    const ids: Record<string, string> = {};
    for (const r of ROLES) {
      const email = `${r.emailPrefix}@${tenant.slug}.test`;
      ids[r.role] = await ensureAuthUser(email, r.fullName);
      // Mirror into public.users
      const { error: upErr } = await supabase
        .from('users')
        .upsert({ id: ids[r.role], email, full_name: r.fullName });
      if (upErr) throw upErr;
      credentials.push({ tenant: tenant.slug, role: r.role, email, password: PASSWORD });
    }

    const managerId = ids.manager;
    const employeeId = ids.employee;
    const employee2Id = ids.employee2;

    // Tenant memberships
    for (const r of ROLES) {
      const managerFk = r.role === 'employee' || r.role === 'employee2' ? managerId : null;
      const { error } = await supabase
        .from('tenant_memberships')
        .upsert(
          {
            tenant_id: tenant.id,
            user_id: ids[r.role],
            role: r.role,
            manager_user_id: managerFk,
          },
          { onConflict: 'tenant_id,user_id' }
        );
      if (error) throw error;
    }

    // Leave balances
    const allocations: Record<string, number> = { vacation: 20, sick: 10, personal: 5 };
    for (const r of ROLES) {
      if (r.role === 'viewer' || r.role === 'admin' || r.role === 'manager') continue;
      for (const [leaveType, days] of Object.entries(allocations)) {
        const { error } = await supabase.from('leave_balances').upsert(
          {
            tenant_id: tenant.id,
            user_id: ids[r.role],
            leave_type: leaveType,
            year: CURRENT_YEAR,
            allocated_days: days,
            used_days: 0,
            pending_days: 0,
            remaining_days: days,
          },
          { onConflict: 'tenant_id,user_id,leave_type,year' }
        );
        if (error) throw error;
      }
    }
  }

  const md = [
    '# Demo credentials',
    '',
    'Generated by `scripts/create_demo_users.ts`. Password for all demo users: `demo1234`.',
    '',
    '| Tenant  | Role     | Email                  |',
    '|---------|----------|------------------------|',
    ...credentials.map((c) => `| ${c.tenant.padEnd(7)} | ${c.role.padEnd(8)} | ${c.email.padEnd(22)} |`),
    '',
  ].join('\n');
  writeFileSync(resolve(process.cwd(), '..', 'docs', 'demo_credentials.md'), md);

  console.log('Demo users created / verified:');
  console.table(credentials);
  console.log('\nWrote docs/demo_credentials.md');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
